#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-packages
  namespace: tanzu-packages
  annotations:
    kapp.k14s.io/change-group: "pkgr"
spec:
  fetch:
    imgpkgBundle:
      image:  #@ "{}:{}".format(data.values.registry.standard.repo,data.values.registry.standard.version)