#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:yaml", "yaml")

#@ def external_dns_values():
#@overlay/match missing_ok=True
#@overlay/match-child-defaults missing_ok=True
namespace: tanzu-system-service-discovery
deployment:
  args:
    - #@ "--txt-owner-id={}".format(data.values.externaldns.ownerid)
    - --provider=rfc2136
    - #@ "--rfc2136-host={}".format(data.values.externaldns.servers)
    - --rfc2136-port=53
    - #@ "--rfc2136-zone={}".format(data.values.externaldns.zone)
    - --rfc2136-insecure
    - --rfc2136-tsig-axfr
    - --source=service
    - --source=ingress
    - --source=contour-httpproxy
    - #@ "--domain-filter={}".format(data.values.externaldns.zone)
  env: []
  securityContext: {}
  volumeMounts: []
  volumes: []
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-values-secret
  namespace: tanzu-packages
stringData:
  change-default-reg-secret.yml: #@ yaml.encode(overlay.apply(external_dns_values()))