#@ load("@ytt:data", "data")
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: #@ data.values.cluster.name
  namespace: #@ data.values.cluster.namespace
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/16"]
    pods:
      cidrBlocks: ["172.20.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: #@ data.values.cluster.version
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 3
          variables:
            overrides:
            - name: vmClass
              value: best-effort-large
    variables:
    - name: trust
      value:
        additionalTrustedCAs:
        - name: harbor-ca
    - name: vmClass
      value: best-effort-medium
    - name: storageClass
      value: #@ data.values.cluster.storageclass
    - name: defaultStorageClass
      value: #@ data.values.cluster.storageclass
    - name: nodePoolVolumes
      value:
      - name: containerd
        capacity:
          storage: 50Gi
        mountPath: /var/lib/containerd
        storageClass: #@ data.values.cluster.storageclass
      - name: kubelet
        capacity:
          storage: 50Gi
        mountPath: /var/lib/kubelet
        storageClass: #@ data.values.cluster.storageclass