apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkc-tmc-sm-00
  namespace: {{vsphere namespace}}
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: {{storageclass}}
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 10Gi
      tkr:  
        reference:
          name: v1.23.15---vmware.1
    nodePools:
    - name: workers
      replicas: 3
      vmClass: best-effort-large
      storageClass: {{storageclass}}
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 10Gi
      tkr:  
        reference:
          name: v1.23.15---vmware.1
  settings:
    storage:
      classes: ["{{storageclass}}"]
      defaultClass: {{storageclass}}