kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tmc-kapp-role-binding
  namespace: tmc-local
subjects:
- kind: ServiceAccount
  name: kapp-sa
  namespace: tmc-local
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-manager-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-manager-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: cert-manager-packages-sa
  namespace: tanzu-packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: external-dns-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: external-dns-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: external-dns-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: external-dns-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: external-dns-packages-sa
  namespace: tanzu-packages